import { Body, Controller, HttpCode, Post, UsePipes, ValidationPipe } from '@nestjs/common';
import { ApiBearerAuth, ApiOperation, ApiTags } from '@nestjs/swagger';

import { ImportService } from './import.service';
import {
    ImportCommitRequest,
    ImportPreviewResponse,
} from './import-preview.dto';

/**
 * Catalog import controller (T8).
 *
 * Plan reference: `apps/backend/src/modules/products/import/import.controller.ts`.
 * Mounted on the existing `ProductsController` URL prefix so the routes live
 * under `/api/products/import/preview` and `/api/products/import/commit`,
 * consistent with the other catalog routes.
 *
 * Nest guards: `UsePipes(ValidationPipe)` ensures the commit body matches
 * `ImportCommitRequest` (whitelist-only).
 */

@ApiTags('products')
@ApiBearerAuth()
@Controller('products/import')
export class ImportController {
    constructor(private readonly importService: ImportService) {}

    @Post('preview')
    @HttpCode(200)
    @ApiOperation({ summary: 'Parse a CSV catalog into a preview payload (no DB writes)' })
    async preview(@Body() body: { csv: string }): Promise<ImportPreviewResponse> {
        return this.importService.preview(body?.csv ?? '');
    }

    @Post('commit')
    @HttpCode(200)
    @UsePipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true }))
    @ApiOperation({ summary: 'Apply a preview previously generated by /import/preview' })
    async commit(@Body() body: ImportCommitRequest): Promise<{ created: number; updated: number; duplicated: number; skipped: number }> {
        return this.importService.commit(body.previewId, body.duplicates);
    }
}